version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: booting-postgres
    environment:
      POSTGRES_DB: booting_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  openldap:
    image: osixia/openldap:1.5.0
    container_name: ldap-server

    environment:
      LDAP_ORGANISATION: "My Organization"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "admin"

    ports:
      - "389:389"
      - "636:636"


volumes:
  postgres-data:
  redis-data: