spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/booting_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  sql:
    init:
      mode: always

  data:
    redis:
      host: localhost
      port: 6379

  ldap:
    urls: ldap://localhost:389
    base: dc=example,dc=com
    username: cn=admin,dc=example,dc=com
    password: admin

jwt:
  secret: 019fd714-bbdc-728e-8db5-dbff94be4e49
  accessExpiration: 900000
  refreshExpiration: 604800000

server:
  port: 8081